// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrOSctpaFwYu89JARoQMuknbhj0cMNzhA',
    appId: '1:457774627078:android:059d6ad4380ad67a150687',
    messagingSenderId: '457774627078',
    projectId: 'todoapp-65d31',
    storageBucket: 'todoapp-65d31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_8DGjbUivpFC8XXiKwtqIabsGgs-Fvjc',
    appId: '1:457774627078:ios:d1121e41f7274357150687',
    messagingSenderId: '457774627078',
    projectId: 'todoapp-65d31',
    storageBucket: 'todoapp-65d31.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_8DGjbUivpFC8XXiKwtqIabsGgs-Fvjc',
    appId: '1:457774627078:ios:d1121e41f7274357150687',
    messagingSenderId: '457774627078',
    projectId: 'todoapp-65d31',
    storageBucket: 'todoapp-65d31.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
